### ISSUE TITLE
Usage with bower

### ISSUE THREAD

**Issue by emielmolenaar** [samrayner/bootstrap-side-navbar#10]
I am trying to include the side navbar in a project I am working on. I am using Laravel 5.3 and with the help of Elixir / Gulp I compile some SASS files to CSS. On of my SASS files includes the following:

```
@import "bower_components/bootstrap-sass/assets/stylesheets/bootstrap";
@import "bower_components/bootstrap-side-navbar/source/assets/stylesheets/navbar-fixed-side.scss";
```

However, compilation fails:

```
Error: File to import not found or unreadable: bootstrap/variables
       Parent style sheet: /home/vagrant/www/office.thetravelspy.dev/bower_components/bootstrap-side-navbar/source/assets/stylesheets/navbar-fixed-side.scss
        on line 1 of bower_components/bootstrap-side-navbar/source/assets/stylesheets/navbar-fixed-side.scss
>> @import 'bootstrap/variables';
```

Apparently the file bootstrap/variables isn't found. I have been fiddling around with settings include paths and such, but that does not make any difference. Am I doing something wrong or isn't this just not going to work?

Thanks!

**Comment by samrayner** [comment]
I haven't actually used Bower. Have you tried simply removing the line `@import 'bootstrap/variables';`? If you're importing the whole of Bootstrap then the variables should already be imported I think.

**Comment by livein21st** [comment]
the dropdown inside navigation is by default open. even not togling. any sugesstion or solution..? Thanks

**Comment by emielmolenaar** [comment]
I have indeed tried that and that "fixes" the issue for me. But, then the whole point of Bower is missed: to install a package and get things working without having to hack code :smile: 

It is working for me now, as I have made a local copy of the source SASS of this package in my versioning system. But I think that is not the way to go. 

Why is the @import line present in the code? It is required to make things work on other systems?

**Comment by samrayner** [comment]
Bower support was added through https://github.com/samrayner/bootstrap-side-navbar/pull/4 so I assume it worked for @HarelM? As I say, I haven't used Bower.

Personally I think having this as a Bower package is of very little benefit as the repo consists of a single stylesheet. I don't have any plans to make regular updates to the stylesheet and it's unlikely that it will break due to Bootstrap 3 changes as the team are focused on Bootstrap 4. I might write a side nav for Bootstrap 4 when that is released but it would be a separate project. Ideally the option would be included in BS4 itself :)

I think copying the `scss` file into your project is the way to go.

**Comment by HarelM** [comment]
Using bower allows updates to be pushed automatically for all the repositories you are using, I can't see how one can work without it (or an equivalent versioning system to all 3rd party dependencies), but that's just me.
It did work for me when I used it but I needed only the css file and not the scss file, BTW if you need something else you can override the bower "main" property for certain repositories.
I needed a toggle-able side bar so I moved to another project, feel free to update the bower.json file to your needs.

**Comment by emielmolenaar** [comment]
All right. Maybe I'll just fork this repo and create a version that suits me. Thanks!
