### ISSUE TITLE
The side navbar with a normal top navbar interfere when collapsing and expanding

### ISSUE THREAD

**Issue by MidasLamb** [samrayner/bootstrap-side-navbar#12]
When the screen is small enough for the button to collapse or uncollapse to become available, clicking on the uncollapse button for the side navbar (which is now at the top) also uncollapses the original top navbar. But uncollapsing the top navbar does not uncollapse the side navbar.

**Comment by samrayner** [comment]
I don't understand what you mean, sorry. Do you have two navbars?

**Comment by MidasLamb** [comment]
Yeah, i have the normal top sidebar that is from bootstrap itself ([link](http://getbootstrap.com/components/#navbar-default) ) and then for certain pages i want your side navbar. But when both are in use and the width of the device is small, pressing the uncollapse button of your side navbar, also uncollapses the normal navbar. I hope this made clear what i meant?

**Comment by samrayner** [comment]
It's not designed to work with a second navbar. They'll end up both collapsing to the top. I would guess start by trying to change the data-target ID though.

**Comment by MidasLamb** [comment]
Fiddling around with the data-target fixed it indeed, thanks for pointing me in the direction i needed to look :)
