### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by HarelM** [samrayner/bootstrap-side-navbar#3]
Is it possible to add bower support for this library, it is very nice and works very well.

**Comment by samrayner** [comment]
Hi @HarelM. Thanks, glad you've found it useful! I'm afraid I don't use Bower. If you have a chance to create a pull request I would be happy to take a look though?

**Comment by HarelM** [comment]
Where do you keep the generated css file? The demo page is referencing raw github location but I could not find it in the repository. Also I don't see any releases here at Github... If you create a release with a css file inside I think I can manage to create a bower package from it.

**Comment by samrayner** [comment]
Thanks @HarelM. I'll try to get round to this on Friday and give you a ping.

**Comment by samrayner** [comment]
@HarelM I've added the compiled CSS and done a v1 release :)

https://github.com/samrayner/bootstrap-side-navbar/blob/source/source/assets/stylesheets/navbar-fixed-side.css
https://github.com/samrayner/bootstrap-side-navbar/releases/tag/v1.0.0

**Comment by HarelM** [comment]
Sorry for nagging, can you make another release called v1.1 or v1.0.1 that has the bower.json file in it?
This repository is now registered but when using bower to get it the bower.json file is missing so bower does not know which file to serve the developer.

**Comment by samrayner** [comment]
https://github.com/samrayner/bootstrap-side-navbar/releases/tag/v1.0.1

If that doesn't work it might be because it needs to be on the master branch? The default branch for this repo is `source`.

**Comment by HarelM** [comment]
It worked like a charm! Thanks!
